# Generated by Django 4.2.5 on 2024-07-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='type',
            field=models.CharField(choices=[('Summer Program', 'Summer Program'), ('Competition', 'Competition'), ('Scholarship', 'Scholarship')], default='Summer Program', max_length=15),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='cost',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='effort',
            field=models.CharField(blank=True, choices=[('Low', 'Low effort'), ('Medium', 'Medium effort'), ('High', 'High effort'), ('Hypercompetitive', 'Hypercompetitive')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.subject'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='year',
            field=models.CharField(blank=True, choices=[('9th', '9th grade'), ('10th', '10th grade'), ('11th', '11th grade'), ('12th', '12th grade')], max_length=4, null=True),
        ),
    ]
